### ISSUE TITLE
Contributors and collaborators needed!

### ISSUE THREAD

**Issue by dportzline83** [dportzline83/RavenMigrations#2]
This organization and fork were created with the hope that it would inspire those that have already worked with and forked the original repository (https://github.com/khalidabuhakmeh/RavenMigrations) to contribute to a central place, as well as encourage contributions from others. I believe there are many useful changes that have already been made in different forks and it would be great to consolidate those in one place! I would also love to see continued long-term contribution to and maintenance of this project through this organization. I have set up a contributing guide, code of conduct, and a build server for this project, all of which are linked from the readme. I'd like to specifically invite all current fork-owners to help contribute, maintain, comment, etc: @daniel-chambers, @ricardobrandao, @rogersillito, @JonasSamuelsson, @danielmarbach. And of course, the original repository owner: @khalidabuhakmeh. If nothing else, come join a discussion in the Gitter room: https://gitter.im/migrating-ravens/RavenMigrations

**Comment by khalidabuhakmeh** [comment]
Hi, send me your nuget username and I will make you an owner of the package. Additionally I can give you commit access to this repo. 

I've been ultra busy and RavenDB is not high on my list at the moment.

**Comment by khalidabuhakmeh** [comment]
You and others are now collaborators on the main repo. Feel free to commit and merge away :)

**Comment by dportzline83** [comment]
Hey, good to hear from you. I think it would be ideal to have this library in an organization. That way we can have multiple owners who can add collaborators, fine-grained permissions, etc. Would you mind just transferring your repository to the organization?

Using the original nuget name would be awesome! My nuget username is dportzline83.

**Comment by dportzline83** [comment]
I made you an owner of this organization, so you should be able to transfer your repository. I just need to rename or move my fork so there's not a name conflict. Let me know if you are willing to do the transfer, and I'll move my fork.

**Comment by khalidabuhakmeh** [comment]
Ok I'll do that, I really want to maintain the nuget package name for existing users

**Comment by khalidabuhakmeh** [comment]
Bah, you have to delete this repo because it is a direct fork and won't let me transfer it. Backup your read me changes and I'll transfer it. 

P.s. On vacation currently

**Comment by khalidabuhakmeh** [comment]
Could you delete this repo?

**Comment by dportzline83** [comment]
I moved the repository to my GitHub account. So, I think that should work instead of deleting it. Let me know if you can transfer now.

**Comment by dportzline83** [comment]
Oh, and I'm sorry to interrupt your vacation!

**Comment by khalidabuhakmeh** [comment]
It worked!!! Send me an email with your nuget username and I'll give you package push access.

**Comment by dportzline83** [comment]
I sent an email to the address listed on your GitHub profile. Let me know if you don't get it.

**Comment by khalidabuhakmeh** [comment]
You are now a nuget owner, thanks for helping.

**Comment by dportzline83** [comment]
Thank you!

**Comment by dportzline83** [comment]
The collaboration on this project should now take place on the original repository, which has been moved to an organization: https://github.com/migrating-ravens/RavenMigrations
